---@module 'lib.nvim.bindings.autocmd.docs'
--- Write what is registered into `bindings/autocmd/` as markdown, one file per
--- event family.
---
--- The want behind it: a plugin's `bindings/` folder should be where you look
--- to find out what the plugin binds, autocmds included -- without moving the
--- autocmds themselves away from the features that own them, which is what
--- makes them readable in the first place. So the folder gets *references*,
--- generated from `lib.nvim.bindings.autocmd`'s registry, and the code stays
--- where it is.
---
--- Markdown, not Lua. A `.lua` file that is really a listing would pretend to
--- be code that runs, and the next reader would look for its callers.
---
--- **Deliberately not automatic.** An earlier shape of this idea had `setup()`
--- write the files whenever the feature was enabled. That is wrong twice over:
--- writing files is a side effect a plugin should not perform unasked, and the
--- directory it would write into is the *installed* plugin directory -- your
--- repo while developing, and a plugin-manager-owned (often read-only) tree
--- for everybody else. So this is a function a plugin exposes behind its own
--- command, or calls from CI, and never from `setup()`.
---
--- **What the output is and is not.** It is what *this session* registered,
--- which depends on the config that ran: a plugin whose features are half
--- switched off registers half the autocmds. The generated header says so and
--- records the run's own settings where the caller passes them. Treat it as a
--- snapshot of one configuration, not as the plugin's full surface.

local M = {}

--- Event families, in output order. First match wins, so the specific
--- prefixes come before the general ones.
---@type { file: string, title: string, match: fun(event: string): boolean }[]
local FAMILIES = {
  {
    file = "buffer.md",
    title = "Buffer",
    match = function(e)
      return e:match("^Buf") ~= nil
    end,
  },
  {
    file = "window.md",
    title = "Window & Tab",
    match = function(e)
      return e:match("^Win") ~= nil or e:match("^Tab") ~= nil
    end,
  },
  {
    file = "cursor.md",
    title = "Cursor & Text",
    match = function(e)
      return e:match("^Cursor") ~= nil or e:match("^Text") ~= nil or e:match("^Insert") ~= nil
    end,
  },
  {
    file = "filetype.md",
    title = "FileType & Syntax",
    match = function(e)
      return e == "FileType" or e == "Syntax" or e == "ColorScheme"
    end,
  },
  {
    file = "lifecycle.md",
    title = "Session lifecycle",
    match = function(e)
      return e:match("^Vim") ~= nil or e:match("^Session") ~= nil or e:match("^Focus") ~= nil
    end,
  },
  {
    file = "other.md",
    title = "Everything else",
    match = function()
      return true
    end,
  },
}

---@internal
--- Which family a record belongs to, by its first event.
---@param record Lib.Autocmd.Record
---@return integer index into FAMILIES
local function family_of(record)
  local first = record.events[1] or ""
  for i, fam in ipairs(FAMILIES) do
    if fam.match(first) then
      return i
    end
  end
  return #FAMILIES
end

---@internal
--- A path relative to `root`, with forward slashes, when it is inside it.
---@param abs string
---@param root string|nil
---@return string
local function relativize(abs, root)
  local path = (abs or "?"):gsub("\\", "/")
  if not root or root == "" then
    return path
  end
  local prefix = root:gsub("\\", "/"):gsub("/+$", "") .. "/"
  if path:sub(1, #prefix) == prefix then
    return path:sub(#prefix + 1)
  end
  return path
end

---@internal
---@param records Lib.Autocmd.Record[]
---@param title string
---@param opts Lib.Autocmd.Docs.Opts
---@return string[]
local function render(records, title, opts)
  local lines = {
    ("# %s autocommands"):format(title),
    "",
    "<!-- GENERATED by lib.nvim.bindings.autocmd.docs — do not edit by hand. -->",
    "",
  }

  if opts.note then
    lines[#lines + 1] = opts.note
    lines[#lines + 1] = ""
  end

  lines[#lines + 1] = "Registered in the session that generated this file. A configuration that"
  lines[#lines + 1] = "switches features off registers fewer of them, so this is a snapshot of one"
  lines[#lines + 1] = "setup, not the plugin's full surface."
  lines[#lines + 1] = ""

  if #records == 0 then
    lines[#lines + 1] = "_None._"
    lines[#lines + 1] = ""
    return lines
  end

  table.sort(records, function(a, b)
    local ae, be = a.events[1] or "", b.events[1] or ""
    if ae ~= be then
      return ae < be
    end
    return (a.group or "") < (b.group or "")
  end)

  lines[#lines + 1] = "| Event | Group | Scope | What | Source |"
  lines[#lines + 1] = "| --- | --- | --- | --- | --- |"

  for _, r in ipairs(records) do
    local scope = "-"
    if r.buffer then
      scope = "buffer-local"
    elseif type(r.pattern) == "table" then
      scope = table.concat(r.pattern, ", ")
    elseif r.pattern then
      scope = tostring(r.pattern)
    end
    lines[#lines + 1] = ("| `%s` | `%s` | %s | %s | `%s` |"):format(
      table.concat(r.events, "`, `"),
      r.group or "-",
      scope,
      r.desc or "_(no desc)_",
      relativize(r.src, opts.root)
    )
  end

  lines[#lines + 1] = ""
  return lines
end

---@class Lib.Autocmd.Docs.Opts
---@field dir string          # Target directory, e.g. "<repo>/lua/<plugin>/bindings/autocmd".
---@field filter? fun(record: Lib.Autocmd.Record): boolean  # Which records belong to this plugin. Default: all.
---@field root? string        # Repo root; source paths are written relative to it.
---@field note? string        # An extra paragraph for the header, e.g. which config produced this.

---@internal
--- The rendered files as `{ [filename] = content }`, without touching disk.
---@param opts Lib.Autocmd.Docs.Opts
---@return table<string, string>
local function build(opts)
  local au = require("lib.nvim.bindings.autocmd")
  local records = au.registered()

  local buckets = {}
  for i = 1, #FAMILIES do
    buckets[i] = {}
  end

  for _, r in ipairs(records) do
    if not opts.filter or opts.filter(r) then
      local i = family_of(r)
      buckets[i][#buckets[i] + 1] = r
    end
  end

  local out = {}
  for i, fam in ipairs(FAMILIES) do
    -- An empty family gets no file rather than a file saying "none": a
    -- directory listing should answer "what kinds of event does this plugin
    -- react to" at a glance, and six files of which four say nothing does not.
    if #buckets[i] > 0 then
      out[fam.file] = table.concat(render(buckets[i], fam.title, opts), "\n")
    end
  end
  return out
end

---Write the files. Creates `opts.dir` if needed.
---@param opts Lib.Autocmd.Docs.Opts
---@return boolean ok
---@return string|nil err
---@return string[] written  # Filenames, for a caller that wants to report them.
function M.write(opts)
  vim.validate("opts", opts, "table")
  vim.validate("dir", opts.dir, "string")

  local files = build(opts)
  if vim.tbl_isempty(files) then
    return false, "nothing registered — call this after setup(), not before", {}
  end

  if vim.fn.isdirectory(opts.dir) == 0 and vim.fn.mkdir(opts.dir, "p") == 0 then
    return false, ("could not create %s"):format(opts.dir), {}
  end

  local written = {}
  for name, content in pairs(files) do
    local path = opts.dir .. "/" .. name
    local fd, err = io.open(path, "w")
    if not fd then
      return false, ("could not write %s: %s"):format(path, tostring(err)), written
    end
    fd:write(content)
    fd:close()
    written[#written + 1] = name
  end

  table.sort(written)
  return true, nil, written
end

---Compare what is on disk against what would be written, without writing.
---
---For the same reason `:DocMap --check` exists: a generated file committed to
---a repository is a claim, and a claim nobody verifies goes stale. Run it in
---CI and the drift is a failed job instead of a wrong document.
---
---Pass the **same** `opts` you passed to `write` -- `note` and `root` are part
---of the rendered output, so a check with different ones reports drift that
---is not there.
---@param opts Lib.Autocmd.Docs.Opts
---@return boolean up_to_date
---@return string[] stale  # Filenames that differ or are missing.
function M.check(opts)
  vim.validate("opts", opts, "table")
  vim.validate("dir", opts.dir, "string")

  local files = build(opts)
  local stale = {}
  for name, content in pairs(files) do
    local fd = io.open(opts.dir .. "/" .. name, "r")
    if not fd then
      stale[#stale + 1] = name
    else
      local on_disk = fd:read("*a")
      fd:close()
      if on_disk ~= content then
        stale[#stale + 1] = name
      end
    end
  end
  table.sort(stale)
  return #stale == 0, stale
end

return M
