---@meta
---@module 'lib.nvim.buf_win_tab.@types.tabs_utils'
-- =========================================================
-- Tabpage Inspection and Formatting
-- =========================================================

--- `tabpage` is a handle, and every Neovim tabpage handle is an integer --
--- `userdata` here was a guess that made both directions of the API a
--- `param-type-mismatch`.
---@alias TabInfo { tabnr: integer, tabpage: integer, wins: integer[], bufs: integer[], current_win: integer, current_buf: integer }
--- Complete tabpage metadata structure.
--- Fields:
---   • tabnr: Tab number (1-based display number)
---   • tabpage: Tabpage handle (userdata from nvim_list_tabpages)
---   • wins: Array of window IDs in this tabpage
---   • bufs: Array of unique buffer IDs visible in this tabpage
---   • current_win: Current/active window ID in this tabpage
---   • current_buf: Buffer ID of current window in this tabpage
---
--- Notes:
---   • bufs are deduplicated (same buffer may appear in multiple windows)
---   • current_win is the window that has focus in this tabpage
---   • tabnr corresponds to :tabnext N argument

---@alias TabReport { count: integer, tabs: TabInfo[], textual: string[] }
--- Structured tabpage report with counts and formatted output.
--- Fields:
---   • count: Total number of tabpages
---   • tabs: Array of TabInfo structures for all tabs
---   • textual: Array of formatted one-line summaries (one per tab)
---
--- Usage:
---   Useful for debugging, status displays, or logging.
---   textual array can be joined with "\n" for multi-line output.

---@class Lib.BufWinTab.TabsUtils
--- Small helper module for inspecting and formatting tabpage information.
--- Read-only; no tabpage modifications.
---
---@field list_tabs fun(): TabInfo[] # Return array of TabInfo for all tabpages. Collects: tab number, tabpage handle, windows, unique buffers, current window, current buffer. Deduplicates buffers visible in multiple windows. Returns complete TabInfo array.
---
---@field format_tab_one_line fun(info: TabInfo): string # Format single TabInfo into concise one-line description. Format: "tab=N wins=W bufs=B cur_buf=C" where N=tab number, W=window count, B=buffer count, C=current buffer ID. Returns formatted string suitable for logging or status display.
---
---@field print_tabs fun(tabs?: TabInfo[]): nil # Pretty-print tabpages to :messages via vim.notify. If tabs=nil, calls list_tabs() automatically. For each tab: prints one-line summary (format_tab_one_line) and detailed buffer list with names. Buffer names formatted as "~:." (relative to home/cwd) or "[no-name]" if empty. Uses DEBUG log level.
---
---@field get_current_tab fun(): TabInfo|nil # Get TabInfo for currently active tabpage. Uses nvim_get_current_tabpage() to determine active tab. Returns TabInfo structure or nil if no current tabpage (should never be nil in practice).
---
---@field get_tab_by_number fun(tabnr: integer): TabInfo|nil # Find and return TabInfo for specific tab number. Searches through list_tabs() output for matching tabnr. Returns TabInfo if found, nil if tab number doesn't exist. Tab numbers are 1-based (same as :tabnext argument).
---
---@field is_single_tab fun(): boolean # Check if only one tabpage is open. Returns true if nvim_list_tabpages() has length <= 1. Useful for "close last tab" or "open new tab" logic.
---
---@field collect_report fun(): TabReport # Collect structured tabpage report with counts and summaries. Returns TabReport structure containing: total count, TabInfo array, array of one-line textual summaries. Useful for debugging, status lines, or comprehensive state snapshots.

return {}
