---@meta
---@module 'lib.lua.time.diff.@types'
-- =========================================================
-- Time Measurement and Interval Tracking
-- =========================================================

---@alias TimeUnit "ns"|"us"|"ms"|"s"
--- Time unit for formatting output.
--- - "ns": Nanoseconds (default, highest precision)
--- - "us": Microseconds
--- - "ms": Milliseconds
--- - "s": Seconds

---@alias TimeDiffIntervalSpec integer|string|number
--- Specifier for an interval in calc_diff().
--- Can be:
--- - Integer (1-10): Checkpoint index (1-based)
--- - String keyword: "average"/"avg", "fastest"/"min", "longest"/"max", "median"/"med"
--- - Large number: Raw time value in nanoseconds

-- =========================================================
-- Core Timer Instance
-- =========================================================

---@class Lib.Time.TimeDiff
--- High-precision timer instance with checkpoint tracking.
--- Each instance maintains independent state and provides:
--- - Nanosecond precision via vim.uv.hrtime()
--- - Multiple checkpoints with automatic interval calculation
--- - Dynamic property access (diff.first, diff.second, ..., diff.last)
--- - Statistical analysis of intervals (min, max, avg, median, stddev, CV)
--- - Pretty-printed output with configurable units
--- - Iterator support with custom labels
--- - Metatable-based callable interface
---
--- Usage:
---   local diff = require("lib.lua.time.diff")()  -- call the factory
---   diff.start()           -- Optional, auto-started on creation
---   local t1 = diff.check("ms")  -- Record checkpoint in milliseconds
---   print(diff.first)      -- Access first checkpoint (always in ns)
---   print(diff("ms"))      -- Print summary in milliseconds
---   print(diff.pretty("ms")) -- Formatted table output
---
--- Important:
--- - All stored values are in nanoseconds internally
--- - Dynamic properties (first, second, etc.) always return nanoseconds
--- - Methods accept optional unit parameter for conversion
--- - Each factory call creates a new independent instance
---
---@field private _start number # Initial timestamp (nanoseconds)
---@field private _checks number[] # List of checkpoint timestamps (nanoseconds)
---@field private _index integer # Iterator index for next()
---@field private _iter_label string|nil # Custom label for iterator output
---@field private _iter_show_index boolean # Whether to show index in iterator output
---
---@field start fun(): nil # Start or reset the timer. Clears all checkpoints and sets new baseline timestamp.
---
---@field check fun(unit?: TimeUnit): number # Record a checkpoint and return elapsed time since start. Can be called multiple times for intermediate intervals. Returns elapsed time in specified unit (default: ns).
---
---@field result fun(unit?: TimeUnit): number|nil # Get total elapsed time since start. Equivalent to last checkpoint if check() was called. Returns nil if no checkpoints exist.
---
---@field get fun(idx: integer, unit?: TimeUnit): number|nil # Get elapsed time of specific checkpoint by index (1-based). Returns nil if index out of bounds [1..n].
---
---@field next fun(label?: string, unit?: TimeUnit): string|number|nil # Iterator: Returns next checkpoint sequentially. Resets to beginning when exhausted. Returns formatted string if label is set (via parameter or reset_iterator), raw number otherwise, or nil when exhausted. Label parameter overrides iterator label for this call only.
---
---@field reset_iterator fun(label?: string, show_index?: boolean): nil # Reset iterator to beginning. Optionally set custom label and enable index display for subsequent next() calls.
---
---@field fastest fun(unit?: TimeUnit): number|nil # Get fastest (minimum) interval between consecutive checkpoints. Returns nil if fewer than 1 checkpoint. Operates on deltas, not cumulative times.
---
---@field longest fun(unit?: TimeUnit): number|nil # Get longest (maximum) interval between consecutive checkpoints. Returns nil if fewer than 1 checkpoint. Operates on deltas, not cumulative times.
---
---@field average fun(unit?: TimeUnit): number|nil # Get average interval between consecutive checkpoints. Returns nil if fewer than 1 checkpoint. Formula: sum(deltas) / count(deltas).
---
---@field median fun(unit?: TimeUnit): number|nil # Get median interval between consecutive checkpoints. Returns nil if fewer than 1 checkpoint. For even count: average of two middle values.
---
---@field stddev fun(unit?: TimeUnit): number|nil # Get standard deviation of intervals. Returns nil if fewer than 2 checkpoints. Measures variation/dispersion of timing. Formula: sqrt(sum((delta - avg)^2) / count).
---
---@field cv fun(): number|nil # Get coefficient of variation (CV) as percentage. Returns nil if fewer than 2 checkpoints. Formula: (stddev / mean) * 100. Interpretation: <10% = very consistent, 10-30% = moderate variation, >30% = high variability.
---
---@field calc_diff fun(iv1: TimeDiffIntervalSpec, iv2: TimeDiffIntervalSpec, unit?: TimeUnit): number|nil # Calculate absolute difference between two intervals. Accepts checkpoint indices (1-10), statistical keywords ("average", "fastest", "longest", "median"), or raw time values in nanoseconds. Always returns positive difference. Returns nil if invalid input.
---
---@field results fun(unit?: TimeUnit): string # Generate summary string with all checkpoint times and statistics. Format: "Check 1: X.XXXns | ... | Total: Z.ZZZns | Fastest: A.AAAns | Longest: B.BBBns | Average: C.CCCns | Range: D.DDDns"
---
---@field pretty fun(unit?: TimeUnit): string # Generate pretty-printed table suitable for :messages or notify windows. Includes columns: Index, Elapsed, Delta. Includes comprehensive statistics section: Fastest Δ, Longest Δ, Average Δ, Median Δ, Range, Std Dev, CV. Multi-line formatted output with box drawing characters.
---
---@field first number|nil # First checkpoint elapsed time (nanoseconds). Same as get(1). Nil if checkpoint doesn't exist. Always in nanoseconds regardless of check() unit.
---
---@field second number|nil # Second checkpoint elapsed time (nanoseconds). Same as get(2). Nil if checkpoint doesn't exist.
---
---@field third number|nil # Third checkpoint elapsed time (nanoseconds). Same as get(3). Nil if checkpoint doesn't exist.
---
---@field fourth number|nil # Fourth checkpoint elapsed time (nanoseconds). Same as get(4). Nil if checkpoint doesn't exist.
---
---@field fifth number|nil # Fifth checkpoint elapsed time (nanoseconds). Same as get(5). Nil if checkpoint doesn't exist.
---
---@field sixth number|nil # Sixth checkpoint elapsed time (nanoseconds). Same as get(6). Nil if checkpoint doesn't exist.
---
---@field seventh number|nil # Seventh checkpoint elapsed time (nanoseconds). Same as get(7). Nil if checkpoint doesn't exist.
---
---@field eighth number|nil # Eighth checkpoint elapsed time (nanoseconds). Same as get(8). Nil if checkpoint doesn't exist.
---
---@field ninth number|nil # Ninth checkpoint elapsed time (nanoseconds). Same as get(9). Nil if checkpoint doesn't exist.
---
---@field tenth number|nil # Tenth checkpoint elapsed time (nanoseconds). Same as get(10). Nil if checkpoint doesn't exist.
---
---@field last number|nil # Last checkpoint elapsed time (nanoseconds). Same as result(). Nil if no checkpoints recorded. Always in nanoseconds.

-- =========================================================
-- Module Factory
-- =========================================================

---@class Lib.Time.Diff
--- Module factory. `require("lib.lua.time.diff")` returns this factory (cached);
--- calling it (`require("lib.lua.time.diff")()`) creates a new independent timer
--- instance, already started.
---
--- Notes:
--- - All values stored in nanoseconds; unit params only affect output.
--- - Statistics operate on the deltas between consecutive checkpoints, e.g.
---   checkpoints 10ms/25ms/50ms -> intervals 10ms/15ms/25ms.
--- - stddev/CV need >= 2 checkpoints; the other stats need >= 1.
--- - The instance is callable: `diff(unit)` and `tostring(diff)` return the
---   summary; `__index` serves the ordinal properties (first..tenth, last).
---
--- See lua/lib/lua/time/diff/README.md for worked examples.

return {}
