---@meta
---@module 'lib.nvim.net.curl.@types'

---Basic auth credentials for `Lib.Net.Curl.FetchOpts.auth` (`-u user:pass`).
---@class Lib.Net.Curl.BasicAuth
---@field user string
---@field pass string

---Options for `require("lib.nvim.net.curl").fetch_json` / `fetch_json_blocking`.
---@class Lib.Net.Curl.FetchOpts
---@field method? string HTTP method (default `"GET"`)
---@field headers? table<string, string> Extra headers, one `-H` per entry
---@field bearer_token? string Sent as `Authorization: Bearer <token>`
---@field secret_headers? table<string, string> Header name/value pairs sent through the same `-K -` config-file path as `bearer_token`/`opts.auth`, never argv — for API-specific credential header names (e.g. Anthropic's `x-api-key`) that `is_secret_header` cannot recognize generically
---@field query? table<string, string> URL-encoded and appended as `?k=v&...`
---@field timeout_ms? integer|false Passed through to `vim.system`'s `timeout` / `wait(timeout)`. `download`/`download_blocking` default to 5 minutes; `false` lifts that default. The fetch tiers have no default.
---@field max_bytes? integer|false Abort once the body would exceed this many bytes (curl's `--max-filesize`). `download`/`download_blocking` default to 512 MiB; `false` lifts that default. The fetch tiers have no default.
---@field body? string Raw request body, sent via `-d`
---@field auth? Lib.Net.Curl.BasicAuth Basic auth (`-u user:pass`)
---@field form? table<string, string> Multipart form fields, one `-F "k=v"` per entry; a value starting with `@` is curl's own file-upload syntax
---@field raw_args? string[] Extra curl arguments appended verbatim — an escape hatch for anything not otherwise covered
---@field http_version? "1.0"|"1.1"|"2" Forces `--http1.0`/`--http1.1`/`--http2`
---@field proxy? string Sent as `-x <proxy>`
---@field insecure? boolean Sent as `-k` (skip TLS certificate verification)

---A response as it actually came back — status, headers, body — undecoded.
---What `fetch_raw`/`fetch_raw_blocking` return on success, in place of
---`fetch_json`'s already-parsed JSON value.
---@class Lib.Net.Curl.RawResponse
---@field status integer HTTP status code, parsed from the response's own status line — curl's process exit code says nothing about this (it is 0 for a successful request regardless of the status returned).
---@field status_text string Reason phrase from the status line (`"OK"`, `"Not Found"`, ...); `""` if the server sent none.
---@field headers table<string, string> Response headers, keys lowercased so a lookup does not depend on a server's own casing convention.
---@field body string Raw response body text, exactly as received.

---Callbacks for `fetch_stream`. `on_chunk` fires once per line of raw
---response body, in order, as it arrives; `on_done` fires once after the
---process exits (even if the request failed — check `raw_obj.code`);
---`on_error` fires if the process itself could not be read from (distinct
---from an HTTP-level error, which still reaches `on_done`).
---@class Lib.Net.Curl.StreamHandlers
---@field on_chunk? fun(line: string)
---@field on_done? fun(raw_obj: vim.SystemCompleted)
---@field on_error? fun(err: string)
--
---@class Lib.Net.Curl
---@field fetch_json fun(url: string, opts: Lib.Net.Curl.FetchOpts|nil, cb: fun(ok: boolean, data_or_err: any, raw_obj: vim.SystemCompleted))
---@field fetch_json_blocking fun(url: string, opts: Lib.Net.Curl.FetchOpts|nil): boolean, any, vim.SystemCompleted
---@field fetch_raw fun(url: string, opts: Lib.Net.Curl.FetchOpts|nil, cb: fun(ok: boolean, response_or_err: Lib.Net.Curl.RawResponse|string, raw_obj: vim.SystemCompleted))
---@field fetch_raw_blocking fun(url: string, opts: Lib.Net.Curl.FetchOpts|nil): boolean, Lib.Net.Curl.RawResponse|string, vim.SystemCompleted
---@field fetch_stream fun(url: string, opts: Lib.Net.Curl.FetchOpts|nil, handlers: Lib.Net.Curl.StreamHandlers): vim.SystemObj
---@field download fun(url: string, dest_path: string, opts: Lib.Net.Curl.FetchOpts|nil, cb: fun(ok: boolean, response_or_err: Lib.Net.Curl.RawResponse|string, raw_obj: vim.SystemCompleted))
---@field download_blocking fun(url: string, dest_path: string, opts: Lib.Net.Curl.FetchOpts|nil): boolean, Lib.Net.Curl.RawResponse|string, vim.SystemCompleted
---@field config_quote fun(value: string): string  Escape a value for a curl config file's quoted-string form; public so a caller building its own argv shares this instead of a second copy.
---@field is_secret_header fun(name: string): boolean  Whether a header name carries a credential and must go through the config-file path rather than argv.
