---@module 'lib.nvim.bindings.usercmd.docs'
--- Write what is registered into `bindings/usercmd/` as markdown.
---@description
--- The sibling of `lib.nvim.bindings.autocmd.docs`, and the same want behind
--- it: a plugin's `bindings/` folder should be where you look to find out what
--- the plugin defines, without moving the definitions away from the features
--- that own them.
---
--- **Why generate this when `nvim_get_commands()` exists.** It does not tell
--- you where a command came from. "Something defines `:CwdHere`" is not
--- actionable; `lua/bindings/usrcmds/init.lua:59` is. The registry records the
--- call site, and that is most of what this page is for. The rest --- `nargs`,
--- `bang`, `range`, completion --- is the shape of the call, which a reader
--- otherwise has to reconstruct from `:command`.
---
--- **Verb trees are elsewhere.** `usercmd.composer` builds `:Verb sub sub ARG`
--- commands and already generates its own reference from the same route tree
--- that drives dispatch (`composer.document()`). This page covers the plain
--- `create()` calls, which had no such thing. A composer verb appears here as
--- the single command it really is, with a pointer rather than a duplicate of
--- its subcommand table.
---
--- **Deliberately not automatic**, for the reason the autocmd writer gives:
--- writing files is a side effect a plugin should not perform unasked, and the
--- directory it would write into is plugin-manager-owned for everybody but the
--- author. This is a function a plugin exposes behind its own command, or calls
--- from CI.

local util = require("lib.nvim.bindings.docs_util")

local M = {}

local FILE = "commands.md"

---@internal
--- Fill in what was not given.
---@param opts Lib.UserCommand.Docs.Opts|nil
---@return Lib.UserCommand.Docs.Opts
local function defaults(opts)
  opts = vim.deepcopy(opts or {})

  -- Level 4: getinfo -> util.caller_file -> defaults -> write/check -> caller.
  local root, plugin = util.repo_of(util.caller_file(4))
  if not root then
    root = (vim.fn.getcwd():gsub("\\", "/"))
  end

  opts.root = (opts.root or root):gsub("\\", "/")

  if not plugin and opts.root then
    local dirs = {}
    for _, e in ipairs(vim.fn.readdir(opts.root .. "/lua") or {}) do
      if vim.fn.isdirectory(opts.root .. "/lua/" .. e) == 1 then
        dirs[#dirs + 1] = e
      end
    end
    if #dirs == 1 then
      plugin = dirs[1]
    end
  end

  if not opts.dir and opts.root and plugin then
    opts.dir = ("%s/lua/%s/bindings/usercmd"):format(opts.root, plugin)
  end

  -- By SOURCE, not by name prefix. A record belongs to this repo if it was
  -- created from a file inside it, which is exactly the question -- and true
  -- regardless of what the plugin chose to call its commands.
  if not opts.filter and opts.root then
    local root_dir = opts.root
    opts.filter = function(r)
      return util.is_under(r.src, root_dir)
    end
  end

  return opts
end

---@internal
--- Names the composer owns, so a verb can point at its own reference instead
--- of pretending to be a flat command.
---@return table<string, true>
local function composer_verbs()
  local ok, registry = pcall(require, "lib.nvim.bindings.usercmd.composer.registry")
  if not ok or type(registry.map) ~= "function" then
    return {}
  end
  local out = {}
  for name in pairs(registry.map()) do
    out[name] = true
  end
  return out
end

---@internal
---@param records Lib.UserCommand.Record[]
---@param opts Lib.UserCommand.Docs.Opts
---@return string[]
local function render(records, opts)
  local lines = {
    "# User commands",
    "",
    "<!-- GENERATED by lib.nvim.bindings.usercmd.docs — do not edit by hand. -->",
    "",
  }

  if opts.note then
    lines[#lines + 1] = opts.note
    lines[#lines + 1] = ""
  end

  lines[#lines + 1] = "Registered in the session that generated this file. A configuration that"
  lines[#lines + 1] = "switches features off registers fewer of them, so this is a snapshot of one"
  lines[#lines + 1] = "setup, not the plugin's full surface."
  lines[#lines + 1] = ""

  if #records == 0 then
    lines[#lines + 1] = "_None._"
    lines[#lines + 1] = ""
    return lines
  end

  local verbs = composer_verbs()

  table.sort(records, function(a, b)
    return a.name < b.name
  end)

  lines[#lines + 1] = "| Command | Args | What | Source |"
  lines[#lines + 1] = "| --- | --- | --- | --- |"

  for _, r in ipairs(records) do
    -- The shape of the call, in the notation `:command` uses, so a reader can
    -- compare the two without translating.
    local args = {}
    if r.nargs ~= nil and r.nargs ~= 0 then
      args[#args + 1] = ("nargs=%s"):format(tostring(r.nargs))
    end
    if r.bang then
      args[#args + 1] = "!"
    end
    if r.range then
      args[#args + 1] = "range"
    end
    if r.complete then
      args[#args + 1] = ("complete=%s"):format(r.complete)
    end
    if r.buffer then
      args[#args + 1] = "buffer-local"
    end

    local what = util.cell(r.desc)
    if verbs[r.name] then
      what = (what ~= "" and (what .. " ") or "")
        .. "_(subcommand tree — see the composer's own reference)_"
    elseif what == "" then
      what = "_(no desc)_"
    end

    lines[#lines + 1] = ("| `:%s` | %s | %s | `%s` |"):format(
      r.name,
      #args > 0 and table.concat(args, ", ") or "-",
      what,
      util.relativize(r.src, opts.root)
    )
  end

  lines[#lines + 1] = ""
  return lines
end

---@internal
---@param opts Lib.UserCommand.Docs.Opts
---@return string|nil content
local function build(opts)
  local usercmd = require("lib.nvim.bindings.usercmd")
  local kept = {}
  for _, r in ipairs(usercmd.registered()) do
    if not opts.filter or opts.filter(r) then
      kept[#kept + 1] = r
    end
  end
  if #kept == 0 then
    return nil
  end
  return table.concat(render(kept, opts), "\n")
end

---Write `bindings/usercmd/commands.md` for the calling repository.
---@param opts Lib.UserCommand.Docs.Opts|nil
---@return boolean ok
---@return string|nil err
---@return string[] written
function M.write(opts)
  vim.validate("opts", opts, { "table", "nil" })
  opts = defaults(opts)
  if type(opts.dir) ~= "string" then
    return false, "could not infer the target directory — pass `dir`", {}
  end

  local content = build(opts)
  if not content then
    return false, "nothing registered — call this after setup(), not before", {}
  end

  if vim.fn.isdirectory(opts.dir) == 0 and vim.fn.mkdir(opts.dir, "p") == 0 then
    return false, ("could not create %s"):format(opts.dir), {}
  end

  local path = opts.dir .. "/" .. FILE
  local fd, err = io.open(path, "w")
  if not fd then
    return false, ("could not write %s: %s"):format(path, tostring(err)), {}
  end
  fd:write(content)
  fd:close()

  return true, nil, { FILE }
end

---Compare what is on disk against what would be written, without writing.
---
---For the same reason the autocmd writer has one: a generated file committed
---to a repository is a claim, and a claim nobody verifies goes stale. Run it in
---CI and the drift is a failed job instead of a wrong document.
---
---Pass the **same** `opts` as `write` — `note` and `root` are part of the
---rendered output.
---@param opts Lib.UserCommand.Docs.Opts|nil
---@return boolean up_to_date
---@return string[] stale
function M.check(opts)
  vim.validate("opts", opts, { "table", "nil" })
  opts = defaults(opts)
  if type(opts.dir) ~= "string" then
    return false, { "could not infer the target directory — pass `dir`" }
  end

  local content = build(opts)
  if not content then
    return false, { "nothing registered" }
  end

  local fd = io.open(opts.dir .. "/" .. FILE, "r")
  if not fd then
    return false, { FILE }
  end
  local on_disk = fd:read("*a")
  fd:close()

  return on_disk == content, on_disk == content and {} or { FILE }
end

---Expose `:<name>` and `:<name>Check` for the calling plugin.
---@param name string|nil  # Default `LibUsercmdDocs`.
---@return nil
function M.create_usercmd(name)
  local base = name or "LibUsercmdDocs"
  local usercmd = require("lib.nvim.bindings.usercmd")
  local notify = require("lib.nvim.notify").create("[lib.usercmd.docs]")

  usercmd.create(base, function()
    local ok, err, written = M.write()
    if not ok then
      notify.warn(err or "could not write")
      return
    end
    notify.info(("wrote %d file(s): %s"):format(#written, table.concat(written, ", ")))
  end, { desc = "Write the registered user commands into bindings/usercmd as markdown" })

  usercmd.create(base .. "Check", function()
    local up_to_date, stale = M.check()
    if up_to_date then
      notify.info("bindings/usercmd is up to date")
    else
      notify.warn("stale: " .. table.concat(stale, ", "))
    end
  end, { desc = "Check bindings/usercmd against what is registered" })
end

return M
