---@module 'lib.nvim.docmap.render.badge'
--- A shields.io-shaped SVG badge for `docmap.doccoverage`'s percentage —
--- hand-rolled, not fetched from shields.io itself: a badge generated by an
--- HTTP call at scan time would make `--check` depend on network
--- availability the same way a `dot`-binary call would, which is exactly why
--- `render/dot.lua` is a text export instead. This is the same reasoning,
--- applied to a badge instead of a graph.
---
--- "flat-square" shaped deliberately: no rounded-corner path math, no
--- gradient — a plain two-rect SVG is trivial to keep byte-deterministic
--- (no timestamp, no random id), which a closer shields.io clone would only
--- complicate for a purely cosmetic gain.

local M = {}

---Rough monospace-ish width estimate — accurate enough for a badge, where
---"close" reads as intentional and a text-measurement dependency (a real
---font metrics table, or shelling out to a browser) would be a large
---dependency for a small cosmetic detail.
---@param s string
---@return integer
local function text_width(s)
  return math.floor(#s * 6.2) + 10
end

---@param label string Left segment text, e.g. "doc coverage".
---@param value string Right segment text, e.g. "82%".
---@param color string Right segment fill, a CSS hex color.
---@return string svg
function M.render(label, value, color)
  local lw, vw = text_width(label), text_width(value)
  local w = lw + vw
  local h = 20

  return table.concat({
    ('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" role="img" '):format(w, h),
    ('aria-label="%s: %s">'):format(label, value),
    ('<rect width="%d" height="%d" fill="#555"/>'):format(lw, h),
    ('<rect x="%d" width="%d" height="%d" fill="%s"/>'):format(lw, vw, h, color),
    '<g fill="#fff" text-anchor="middle" ',
    'font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">',
    ('<text x="%d" y="14">%s</text>'):format(lw / 2, label),
    ('<text x="%d" y="14">%s</text>'):format(lw + vw / 2, value),
    "</g></svg>\n",
  })
end

---Colour thresholds shields.io itself uses for a coverage-shaped metric —
---not an aesthetic choice, a familiar one: a reader who has seen any
---shields.io coverage badge already knows what green/yellow/red mean here.
---@param pct number 0-100
---@return string hex
function M.color_for(pct)
  if pct >= 90 then
    return "#4c1"
  elseif pct >= 70 then
    return "#dfb317"
  end
  return "#e05d44"
end

return M
