---@meta
---@module 'lib.nvim.docmap.@types'

---Configuration for a docmap run. Every field that could hardcode a
---particular repo's layout is an option, so other plugins can point docmap at
---their own tree.
---@class Lib.Docmap.Opts
---@field root string Absolute path to the repository root.
---@field source? string Directory to scan, relative to `root`. Default "lua".
---@field lua_root? string Directory the Lua module path is relative to. Default "lua".
---@field title? string Display name for the root node. Default: the source directory name.
---@field types_dir? string Directory name holding type definitions, treated as a module attribute. Default "@types".
---@field out_dir? string Output directory, relative to `root`. Default "docs/map".
---@field repo_url? string Base URL used to build source links (e.g. "https://github.com/user/repo").
---@field branch? string Branch used in source links. Default "main".
---@field extra_checks? Lib.Docmap.Check[] Repo-specific drift checks appended to the generic ones.
---@field calls_heuristic? boolean Also emit call edges whose target was guessed by unique-name match rather than resolved through a require alias. Off by default — a wrong call graph is worse than an incomplete one. Default false.
---@field dead_code? boolean Also report *published* functions with no caller in the tree as dead-code candidates. Off by default, and that is not timidity: a library consists of functions with no internal caller by design, so this reports much of the public API on any tree that is a library. The always-on half of the check — file-local and `@internal` functions — needs no flag because there the statement holds. Default false.
---@field layers? Lib.Docmap.LayerRule[] Module-prefix layering rules for the `layer-violation` check. Empty/absent disables the check.
---@field luals? boolean Merge `lua-language-server --doc` output into the IR (class/alias/field detail, type-reference edges). Off by default — a full-tree run costs real seconds. Default false.
---@field luals_timeout_ms? integer Kill the `lua-language-server --doc` run after this long. Default 60000.
---@field command_name? string Passed to `docmap.command.setup`: register a user command under this name. Default "LibMap".
---@field browse_command_name? string Passed to `docmap.command.setup`: register the editor-side map browser under this name. Default "LibBrowse".
---@field watch? boolean `install()` only: rescan on `BufWritePost` under `source/**.lua`, debounced. Default false.
---@field watch_ms? integer `install()` only: debounce interval for `watch`. Default 500.
---@field tag_files? table<string, string> Doxygen `TAGFILES` equivalent: module-prefix -> another project's `docs/map`-shaped directory (must contain a committed `module_map.json`). A `requires_external` module matching the prefix resolves against that project's own artifact instead of staying an inert box. Local paths only — read synchronously during `scan_full()`, same as `opts.root` itself, so `--check` stays deterministic and offline. See `tagfiles.lua`.
---@field tests_dir? string Directory (relative to `root`) scanned for auto-derived test coverage — see `coverage.lua`. Default "docs/TESTS". A missing directory is not an error: every function is simply left `tested = false`.
---@field badge? boolean Write `coverage.svg` (a shields.io-shaped doc-coverage badge, see `doccoverage.lua`/`render/badge.lua`) alongside the other artifacts. Off by default — most consumers of `generate()` do not want an extra committed file they never asked for. Default false.

---A repo-specific drift check.
---@alias Lib.Docmap.Check fun(ir: Lib.Docmap.IR, opts: Lib.Docmap.Opts): Lib.Docmap.Finding[]

---One layering rule: modules whose `@module` starts with `from` may not
---require modules whose `@module` starts with `to`. Both are plain prefixes,
---not patterns — `lib.vim` matches `lib.vim.buffer` but never `lib.vimx`.
---@class Lib.Docmap.LayerRule
---@field from string Module prefix of the requiring side.
---@field to string Module prefix that side must not reach into.
---@field why string? Appended to the finding message.

---@alias Lib.Docmap.Severity "error"|"warn"|"info"

---@alias Lib.Docmap.Kind
---| "module"    # A directory containing init.lua
---| "namespace" # A directory without init.lua, grouping others
---| "file"      # A non-init.lua Lua file

---One node of the map.
---@class Lib.Docmap.Node
---@field id string Stable identifier — the repo-relative path.
---@field kind Lib.Docmap.Kind
---@field name string Display name (directory or file name).
---@field path string Repo-relative path to the directory or file.
---@field source string? Repo-relative path to the Lua source backing this node.
---@field module string? The declared `---@module` path.
---@field summary string One-sentence description, from the header block.
---@field body string Remaining header prose.
---@field readme string? Repo-relative path to a sibling README.md.
---@field types string[] Repo-relative paths of the module's type files.
---@field export ("function"|"table"|"other"|"none")? Export shape of the source file.
---@field parent string? Parent node id.
---@field depth integer Distance from the root node.
---@field children string[] Child node ids, directories first, then files.
---@field types_detail Lib.Docmap.TypeInfo[]? `@class`/`@alias` detail for this node's `types` files, from `lua-language-server --doc`. `nil` when LuaLS enrichment did not run; `{}` is a real "ran, found nothing here" result.
---@field functions Lib.Docmap.FunctionInfo[] Documented functions found in this node's own source file (not its `@types/` files). Always an array, never nil — unlike `types_detail`, this runs unconditionally as part of `scan()`, no LuaLS required.
---@field requires string[] Node ids this node requires, sorted. Derived from `ir.edges`; an index for convenience, not a second source of truth.
---@field required_by string[] Node ids that require this node, sorted. Same derivation.
---@field requires_external string[] Module paths this node requires that resolve to nothing in the scanned tree — other plugins, or anything outside `source`. Plain strings, not invented nodes: the map only claims to describe what it scanned. The Deps view can draw them on request.
---@field requires_raw Lib.Docmap.RawRequire[] Unresolved `require` occurrences. Internal to the scan pipeline (`deps`/`calls` consume it); deliberately not serialized into `module_map.json`.
---@field calls_raw Lib.Docmap.RawCall[] Unresolved call sites. Internal, same as `requires_raw`.
---@field symbols Lib.Docmap.SymbolInfo[] Module-scope tables, constants and bindings in this node's own source. Always an array; runs unconditionally as part of `scan()`.
---@field stats Lib.Docmap.Stats Counts over this node and everything below it.

---A single `@class`/`@alias` parsed from `lua-language-server --doc` output,
---attached to whichever node owns the file it's defined in.
---@class Lib.Docmap.TypeInfo
---@field name string Fully-qualified type name, e.g. "Lib.Docmap.Node".
---@field kind "class"|"alias"
---@field desc string
---@field file string Repo-relative file the type is defined in.
---@field fields Lib.Docmap.TypeField[] Empty for aliases and field-less classes.
---@field extends string[] Parent class names as written in `---@class Child : A, B`, in source order. Always an array (empty when the class has no parent, and for every alias). Names are kept even when the parent is not declared anywhere in the tree — those simply produce no `"extends"` edge, the same way `requires_external` keeps a require whose target lives outside the map.

---@class Lib.Docmap.TypeField
---@field name string
---@field view string Raw LuaCATS type text, e.g. "table<string, Lib.Docmap.Node>".
---@field desc string

---One `---@param` on a documented function.
---@class Lib.Docmap.ParamInfo
---@field name string
---@field type string Raw LuaCATS type text.
---@field optional boolean Declared as `name?`.
---@field desc string

---One `---@return` on a documented function. LuaLS allows a bare type with no
---name (`---@return boolean`); `name` is nil in that case.
---@class Lib.Docmap.ReturnInfo
---@field type string Raw LuaCATS type text.
---@field name string?
---@field desc string

---A single documented function, extracted via `lib.nvim.docmap.functions`
---(a `vim.treesitter` query, not `lua-language-server --doc` — see that
---module's header for why). Attached to whichever node owns the file it's
---defined in.
---@class Lib.Docmap.FunctionInfo
---@field name string Qualified name as written, e.g. "M.scan_full" or "M.bar".
---@field signature string Name + parameter list, e.g. "scan_full(opts)".
---@field summary string One-line prose from the doc block, if any.
---@field line integer 1-based line the function definition starts on.
---@field params Lib.Docmap.ParamInfo[]
---@field returns Lib.Docmap.ReturnInfo[]
---@field generic string[] `@generic` type names, if any.
---@field deprecated string? `@deprecated` text; nil when not deprecated.
---@field async boolean
---@field nodiscard boolean
---@field local_refs integer How often this function's bare name is mentioned elsewhere in its own file. Answers the one question call edges cannot: a function passed as a *value* (`vim.system(cmd, on_exit)`) is used but never appears at a call site. Deliberately coarse — an unrelated `x.read` counts toward a local `read` — because over-counting errs toward "used", which is the safe direction.
---@field internal boolean Declared `---@internal`: part of the implementation, not of the module's published surface. Sharpens every question of the form "is this used" — `undocumented-param` skips it, the diff counts it as a helper, and a dead-function report can trust it.
---@field tested boolean Set by `coverage.resolve` (R2): this function's bare name is mentioned somewhere under `opts.tests_dir`. `false` until `coverage.resolve` has run, and even then means "not found by name in a spec" rather than "definitely untested" — see that module's header for the blind spot.
---@field see string[] Raw `@see` targets, unresolved — `docmap.check` validates them.
---@field overload string[] Raw `@overload` signatures, unparsed (rendered as-is).
---@field todo string[] `@todo` entries, one per occurrence. Collected into the Notes tab's aggregate list, the way Doxygen's `\todo` feeds its Todo List.
---@field bug string[] `@bug` entries, one per occurrence.
---@field test string[] `@test` entries, one per occurrence.
---@field example string? `@example` block text, if any.
---@field since string? `@since` text, if any.

---What kind of relationship an edge in `ir.edges` records. One array with a
---discriminator rather than three parallel arrays, so layout, filtering and
---drawing exist once each instead of once per relationship.
---@alias Lib.Docmap.EdgeKind
---| "type"    # A `---@field` on one class names another class.
---| "extends" # One class inherits from another (`---@class Child : Parent`).
---| "require" # One file calls `require` on another module in the tree.
---| "call"    # One function calls another.

---What a module-scope binding turned out to be. Deliberately coarse: the
---distinction that matters when reading a module is "lookup table" vs "tuned
---number" vs "something computed at load time", not a type.
---@alias Lib.Docmap.SymbolKind
---| "table"    # Bound to a table constructor.
---| "constant" # Bound to a literal number, string or boolean.
---| "binding"  # Anything else evaluated at load time.

---One module-scope table, constant or binding, from `lib.nvim.docmap.symbols`.
---Functions and `require` bindings are excluded — `docmap.functions` and
---`docmap.deps` own those.
---@class Lib.Docmap.SymbolInfo
---@field name string As written, e.g. "CACHE" or "M.defaults".
---@field kind Lib.Docmap.SymbolKind
---@field detail string Short right-hand-side summary: "12 fields" for a table, the literal for a constant, a condensed expression otherwise.
---@field summary string One-line prose from the doc block above it, if any.
---@field line integer 1-based line the binding starts on.

---Counts over a node and everything below it. Aggregated rather than own-only:
---the question a directory answers is "how big is this part of the tree".
---@class Lib.Docmap.Stats
---@field modules integer Directories with an `init.lua`.
---@field namespaces integer Directories without one.
---@field files_lua integer `.lua` files, including `init.lua` and `@types/`.
---@field files_md integer Markdown files, including READMEs.
---@field files_other integer Everything else that is not a directory.
---@field lines integer Lines of Lua.
---@field functions integer Documented top-level functions.
---@field symbols integer Module-scope tables, constants and bindings.
---@field types integer `@class`/`@alias` definitions — only non-zero once LuaLS enrichment ran.

---A directed edge between two nodes. Which of the optional fields are set is
---determined by `kind` — see each field. `ir.edges` is always an array, empty
---when nothing produced edges, so renderers never need a presence check.
---@class Lib.Docmap.Edge
---@field kind Lib.Docmap.EdgeKind
---@field from string Node id of the referencing/requiring/calling side.
---@field to string Node id of the referenced/required/called side.
---@field from_class string? `kind="type"|"extends"`: fully-qualified name of the referencing/inheriting class.
---@field to_class string? `kind="type"|"extends"`: fully-qualified name of the referenced/inherited class.
---@field via string? `kind="type"`: field name that carries the reference. Absent for `"extends"`, where nothing mediates the relationship.
---@field to_module string? `kind="require"`: the module path as written in the `require` call.
---@field deferred boolean? `kind="require"`: every occurrence sits inside a function body, so this is a lazy load rather than a load-time dependency. Absent means at least one load-time require.
---@field from_fn string? `kind="call"`: declared name of the calling function, e.g. "M.generate".
---@field to_fn string? `kind="call"`: declared name of the called function.
---@field line integer? `kind="require"|"call"`: 1-based line of the call site.
---@field confidence Lib.Docmap.Confidence? `kind="call"`: how the target was determined.

---How a call edge's target was determined. `"exact"` means the callee was
---resolved through a `require` alias, the module's own export table, or a
---file-local function — a syntactic fact. `"heuristic"` means the name matched
---exactly one function in the whole tree and nothing else pinned it down; only
---produced when `opts.calls_heuristic` is set, and drawn differently.
---@alias Lib.Docmap.Confidence "exact"|"heuristic"

---One `require(...)` occurrence as found in a source file, before it is
---resolved against the map. `alias` is set for the `local x = require("y")`
---form, which is what makes call resolution possible at all.
---@class Lib.Docmap.RawRequire
---@field module string The module path as written.
---@field alias string? Local name it was bound to, if any.
---@field member string? Trailing field access, as in `local x = require("y").z`.
---@field deferred boolean? The call sits inside a function body — a lazy load, not a load-time dependency.
---@field line integer

---One call site as found in a source file, before it is resolved against the
---map. `callee` is the raw text of the called expression (`fs.read`, `M.foo`,
---`helper`), `from_fn` the declared name of the top-level function it sits in.
---@class Lib.Docmap.RawCall
---@field callee string
---@field from_fn string?
---@field line integer

---One added or removed require edge in a `Lib.Docmap.Diff`.
---@class Lib.Docmap.DiffEdge
---@field edge string `"<from id> -> <to id>"`.
---@field deferred boolean? The edge is a lazy require.
---@field changed boolean? The edge existed before but stopped being lazy — a load-time dependency that did not exist previously, which is how initialisation cycles get introduced.

---What one revision changed about the *shape* of the tree, from
---`lib.nvim.docmap.diff`.
---@class Lib.Docmap.Diff
---@field nodes_added string[] Node ids, sorted.
---@field nodes_removed string[]
---@field functions_added string[] `"<node id>#<declared name>"`, sorted.
---@field functions_removed string[]
---@field deps_added Lib.Docmap.DiffEdge[]
---@field deps_removed Lib.Docmap.DiffEdge[]
---@field deps_comparable boolean False when the older map predates the dependency graph, in which case the dependency, cycle and impact sections are empty because they are unknowable, not because nothing changed.
---@field cycles_added string[] Load-time cycles introduced.
---@field cycles_removed string[]
---@field impact_changed { id: string, before: integer, after: integer }[] Sorted by how much the blast radius moved.

---A drift finding.
---@class Lib.Docmap.Finding
---@field severity Lib.Docmap.Severity
---@field check string Stable check identifier, e.g. "missing-summary".
---@field node string? Node id the finding attaches to.
---@field message string Human-readable description.

---Metadata about a scan. Deliberately carries no timestamp: a generated-at
---field would make every regeneration a diff even when nothing changed, which
---defeats `--check`.
---@class Lib.Docmap.Meta
---@field title string
---@field source string
---@field types_dir string
---@field repo_url string?
---@field branch string
---@field schema integer IR schema version.
---@field counts table<string, integer> Node counts per kind.

---A `requires_external` module resolved against another project's own
---committed docmap artifact (`opts.tag_files`) — Doxygen `TAGFILES`
---equivalent. `html` is a path to that project's generated page with a bare
---`#<node id>` fragment, the same shorthand a hand-typed or shared link uses.
---@class Lib.Docmap.TagLink
---@field title string The resolved node's `module` (or `name` if declared none).
---@field html string Path to the external project's `index.html`, with a `#<node id>` fragment.

---The intermediate representation every renderer and check reads.
---@class Lib.Docmap.IR
---@field meta Lib.Docmap.Meta
---@field root string Root node id.
---@field order string[] All node ids in deterministic walk order.
---@field nodes table<string, Lib.Docmap.Node>
---@field edges Lib.Docmap.Edge[] Type-reference edges from LuaLS enrichment. Always an array, empty when `opts.luals` did not run.
---@field tag_links table<string, Lib.Docmap.TagLink> `requires_external` modules resolved through `opts.tag_files`. Always a table, empty when `opts.tag_files` is unset or nothing resolved — unlike `types_detail`, resolving is local and cheap, so there is no "did this run" question worth a nil.

---A live handle returned by `docmap.install()`. Keeps a scanned IR in memory
---and, optionally, keeps it fresh — the object-in-source-code counterpart to
---the file-based `generate()`/`:LibMap` path.
---@class Lib.Docmap.Handle
---@field root string The root this handle was installed for; the registry key.
---@field ir fun(): Lib.Docmap.IR Current IR (already scanned; never triggers a scan itself).
---@field findings fun(): Lib.Docmap.Finding[] Current drift findings.
---@field node fun(id: string): Lib.Docmap.Node? Single node lookup on the current IR.
---@field requires fun(id: string): Lib.Docmap.Edge[] Require edges out of this node.
---@field required_by fun(id: string): Lib.Docmap.Edge[] Require edges into this node.
---@field callees fun(fn_key: string): Lib.Docmap.Edge[] Call edges out of a function, keyed `"<node id>#<declared name>"` — the same id scheme the HTML map uses.
---@field callers fun(fn_key: string): Lib.Docmap.Edge[] Call edges into a function, same key scheme.
---@field rescan fun(opts?: { luals?: boolean }): Lib.Docmap.IR, Lib.Docmap.Finding[] Force a rescan now; notifies `on_change` subscribers same as a watch-triggered one.
---@field on_change fun(cb: fun(ir: Lib.Docmap.IR, findings: Lib.Docmap.Finding[])): fun() Subscribe; returns an unsubscribe function.
---@field uninstall fun() Equivalent to `docmap.uninstall(handle)`.

---@class Lib.Docmap
---@field scan fun(opts: Lib.Docmap.Opts): Lib.Docmap.IR
---@field check fun(ir: Lib.Docmap.IR, opts: Lib.Docmap.Opts): Lib.Docmap.Finding[]
---@field scan_full fun(opts: Lib.Docmap.Opts): Lib.Docmap.IR, Lib.Docmap.Finding[] `scan` + optional LuaLS merge (`opts.luals`) + `check`, in one call. What `generate()` and `install()` both build on.
---@field generate fun(opts: Lib.Docmap.Opts): Lib.Docmap.IR, Lib.Docmap.Finding[], string[]
---@field install fun(opts: Lib.Docmap.Opts): Lib.Docmap.Handle
---@field uninstall fun(handle: Lib.Docmap.Handle|string): boolean Accepts a handle or a root path.
---@field render table
