---@module 'lib.nvim.bindings.usercmd.composer.docgen'
--- Generate a deterministic Markdown reference by walking each verb's route
--- tree — the same tree that drives dispatch and completion, so docs can never
--- drift from behavior. Writes via lib.nvim.fs.write.to_file (creates dirs).

local tree = require("lib.nvim.bindings.usercmd.composer.tree")
local format = require("lib.nvim.bindings.usercmd.composer.format")
local write_to_file = require("lib.nvim.fs.write.to_file")

local M = {}

local BEGIN = "<!-- lib.nvim:composer -->"
local END = "<!-- /lib.nvim:composer -->"

---@internal
--- Escape a pipe so a cell never breaks the Markdown table row it sits in.
---
--- Backticks do not help here: GitHub splits a table row on its pipes before
--- it parses inline code, so `` `[--buffer|-b]` `` becomes two cells and every
--- cell past the header's column count is dropped -- silently, and only when
--- rendered. Locally the file still looks right.
---@param s string
---@return string
local function cell(s)
  -- The outer parentheses drop `gsub`'s second return value (the match
  -- count), which this function does not promise.
  return ((s or ""):gsub("|", "\\|"))
end

--- Render one verb section.
---@param name string
---@param spec Lib.UserCmd.Composer.Spec
---@param root Lib.UserCmd.Composer.Node
---@return string
function M.section(name, spec, root)
  local lines = { ("## :%s"):format(name), "" }
  if spec.desc and spec.desc ~= "" then
    lines[#lines + 1] = spec.desc
    lines[#lines + 1] = ""
  end

  lines[#lines + 1] = "| Invocation | Description |"
  lines[#lines + 1] = "| --- | --- |"

  if spec.default then
    lines[#lines + 1] = ("| `:%s` | %s |"):format(name, cell("(bare) default action"))
  end

  local notes = {}
  tree.each_route(root, function(route)
    -- The invocation needs `cell` as much as the description does, and needed
    -- it more in practice: an alternation flag like `[--buffer|-b]` only ever
    -- appears in this column. It went unescaped from the day this was written,
    -- which cost sandbox.nvim 16 command descriptions and casedesk.nvim 11 --
    -- all of them present in the file, none of them rendered.
    lines[#lines + 1] = ("| `%s` | %s |"):format(
      cell(format.invocation(name, route)),
      cell(route.desc or "")
    )
    for _, n in ipairs(format.enum_notes(route)) do
      notes[n] = true
    end
  end)

  -- De-duplicated enum notes below the table.
  local note_list = {}
  for n in pairs(notes) do
    note_list[#note_list + 1] = n
  end
  table.sort(note_list)
  if #note_list > 0 then
    lines[#lines + 1] = ""
    for _, n in ipairs(note_list) do
      lines[#lines + 1] = n .. "  "
    end
  end

  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

--- Render the full document body for a list of {name, spec, root} entries.
---@param entries { name: string, spec: Lib.UserCmd.Composer.Spec, root: Lib.UserCmd.Composer.Node }[]
---@return string
function M.render(entries)
  local parts = {
    "# User commands",
    "",
    "> Generated by `lib.nvim.bindings.usercmd.composer`. Do not edit by hand.",
    "",
  }
  for _, e in ipairs(entries) do
    parts[#parts + 1] = M.section(e.name, e.spec, e.root)
  end
  return table.concat(parts, "\n")
end

---@internal
--- Splice a generated block between BEGIN/END markers in existing content,
--- appending the block (with markers) if they are absent.
---@param existing string
---@param block string
---@return string
local function splice_section(existing, block)
  local wrapped = BEGIN .. "\n" .. block .. "\n" .. END
  if existing:find(BEGIN, 1, true) and existing:find(END, 1, true) then
    local pre = existing:sub(1, existing:find(BEGIN, 1, true) - 1)
    local post = existing:sub(select(2, existing:find(END, 1, true)) + 1)
    return pre .. wrapped .. post
  end
  local sep = (existing ~= "" and not existing:match("\n$")) and "\n\n" or "\n"
  return existing .. sep .. wrapped .. "\n"
end

--- Write the rendered docs for `entries` to `path` in the given mode.
---@param entries table[]
---@param path string
---@param mode "replace"|"section"
---@return boolean ok, string|nil err
function M.write(entries, path, mode)
  local body = M.render(entries)
  if mode == "section" then
    local existing = ""
    local f = io.open(path, "r")
    if f then
      existing = f:read("*a") or ""
      f:close()
    end
    return write_to_file(path, splice_section(existing, body))
  end
  return write_to_file(path, body)
end

return M
