---@meta
---@module 'lib.@types'
-- =========================================================
-- All Lib Modules
-- =========================================================

--- CDX: `Lib.Modules` has no `---@type` referent anywhere in the repo and has
--- CDX: drifted from the real surface (`notifier Lib.Notify+` — stray `+`, and the
--- CDX: aggregate key is `notify`). Likely superseded by `Lib` in
--- CDX: @types/all_functions.lua; left as-is pending an external-consumer check.
---@class Lib.Modules
---@field autocmd Lib.AutoCmd
---@field bufwintab Lib.BufWinTab
---@field buffer Lib.Buffer
---@field cross Lib.Cross
---@field deps Lib.Deps
---@field functions Lib.Functions
---@field frecency Lib.Frecency
---@field fs Lib.Fs
---@field git Lib.Git
---@field json Lib.JSON
---@field lazy Lib.Lazy
---@field lua_ls Lib.LuaLS
---@field map Lib.Map
---@field memo Lib.Memo
---@field normalize Lib.Normalize
---@field notifier Lib.Notify+
---@field nvim Lib.Nvim
---@field progress Lib.Progress
---@field require Lib.Require
---@field strings Lib.Strings
---@field system Lib.System
---@field tables Lib.Tables
---@field terminals Lib.Terminal
---@field time Lib.Time
---@field ui Lib.UI
---@field usrcmd Lib.UsrCmd

return {}
